### ISSUE TITLE
fix images responsive sizes in branching-page

### ISSUE THREAD

**Issue by Vineethaveerapu** [maysunktong/assignment-gitguide#19]
update the width and height for all images in your page
use this and also update other images styles to same,

.branch_image {
    height: auto;
    max-width: 100%;
}

check this screenshot, 

<img width="715" alt="Screenshot 2024-10-19 at 12 20 53" src="https://github.com/user-attachments/assets/1cb1061b-408e-4c02-b8dd-4d334d4dfd14">

**Comment by Ankitasingh88** [comment]
Fixed in https://github.com/maysunktong/assignment-gitguide/pull/21
